server:
  port: 8888
spring:
  cloud:
    config:
      server:
        svn:
          uri: https://subversion.assembla.com/svn/batusel.demo/
          passphrase: 7548b4639b0ca8bedfaf
          default-label: trunk
  profiles:
    active: subversion